filter_secrets: false
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::6}
    - REPO=mayadata/charthub-litmuschaos-io
    - STAG_REPO=mayadata/charthub-litmuschaos-io-stag
sudo: required
services:
- docker
script:
- docker build -t $REPO:$COMMIT -f Dockerfile.client .
- cd ./server
- docker build -t ${REPO}-server:$COMMIT -f Dockerfile.server .
after_success:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then docker login -u "$DOCKER_USER" -p "$DOCKER_PASS";
   docker push $REPO:$COMMIT && docker push ${REPO}-server:$COMMIT;
  fi
- if [ "$TRAVIS_BRANCH" = "staging" -a "$TRAVIS_PULL_REQUEST" != "false" ]; then docker login -u "$DOCKER_USER" -p "$DOCKER_PASS";
   docker tag $REPO:$COMMIT $STAG_REPO:$COMMIT && docker tag ${REPO}-server:$COMMIT ${STAG_REPO}-server:$COMMIT &&  docker push $REPO:$COMMIT && docker push ${REPO}-server:$COMMIT;
  fi  
