packageName: openebs
experiments:
  
  - name: openebs_pool_failure
    CSV: openebs_pool_failure.chartserviceversion.yaml 
    desc: "openebs-pool-failure"
  - name: openebs_target_failure
    CSV: openebs_target_failure.chartserviceversion.yaml 
    desc: "openebs-target-failure"
  - name: openebs_target_network_delay
    CSV: openebs_target_network_delay.chartserviceversion.yaml 
    desc: "openebs-target-network-delay"
  - name: openebs_target_network_loss
    CSV: openebs_target_network_loss.chartserviceversion.yaml 
    desc: "openebs-target-network-loss"
    
